/** REST path templates — use with `apiClient` when backend is wired. */
export const endpoints = {
  auth: {
    login: '/v1/auth/login',
    refresh: '/v1/auth/refresh',
    logout: '/v1/auth/logout',
    forgot: '/v1/auth/forgot-password',
    reset: '/v1/auth/reset-password',
  },
  dashboard: {
    executive: '/v1/dashboard/executive',
  },
  fleet: {
    list: '/v1/vehicles',
    one: (id: number | string) => `/v1/vehicles/${id}`,
    maintenanceAlerts: '/v1/maintenance/alerts',
    maintenanceCalendar: '/v1/maintenance/calendar',
    complianceAlerts: '/v1/compliance/alerts',
    insurancePolicies: (id: number | string) => `/v1/vehicles/${id}/insurance-policies`,
    insurancePolicy: (id: number | string) => `/v1/insurance-policies/${id}`,
    technicalInspections: (id: number | string) => `/v1/vehicles/${id}/technical-inspections`,
    technicalInspection: (id: number | string) => `/v1/technical-inspections/${id}`,
  },
  customers: {
    list: '/v1/customers',
    one: (id: number | string) => `/v1/customers/${id}`,
  },
  contracts: {
    list: '/v1/contracts',
    one: (id: number | string) => `/v1/contracts/${id}`,
    approve: (id: number | string) => `/v1/contracts/${id}/approve`,
    activate: (id: number | string) => `/v1/contracts/${id}/activate`,
    terminate: (id: number | string) => `/v1/contracts/${id}/terminate`,
    installments: (id: number | string) => `/v1/contracts/${id}/installments`,
    generateSchedule: (id: number | string) => `/v1/contracts/${id}/generate-schedule`,
    generatePdf: (id: number | string) => `/v1/contracts/${id}/generate-pdf`,
  },
  documents: {
    list: '/v1/documents',
    upload: '/v1/documents/upload',
    expiring: '/v1/documents/expiring',
    one: (id: string) => `/v1/documents/${id}`,
    download: (id: string) => `/v1/documents/${id}/download`,
    byEntity: (entityType: string, entityId: string | number) => `/v1/entities/${entityType}/${entityId}/documents`,
    generateInvoicePdf: (id: number | string) => `/v1/invoices/${id}/generate-pdf`,
  },
  credit: {
    applications: '/v1/credit-applications',
    one: (id: number | string) => `/v1/credit-applications/${id}`,
    score: (id: number | string) => `/v1/credit-applications/${id}/score`,
    scores: (id: number | string) => `/v1/credit-applications/${id}/scores`,
    latestScore: (id: number | string) => `/v1/credit-applications/${id}/latest-score`,
    decision: (id: number | string) => `/v1/credit-applications/${id}/decision`,
  },
  contractTemplates: {
    list: '/v1/contract-templates',
    one: (id: number | string) => `/v1/contract-templates/${id}`,
  },
  finance: {
    schedule: '/v1/finance/schedule',
    payments: '/v1/finance/payments',
  },
  arrears: {
    cases: '/v1/arrears/cases',
  },
  usedCars: {
    listings: '/v1/used-cars/listings',
  },
  gps: {
    positions: '/v1/gps/positions',
    vehiclesLive: '/v1/gps/vehicles/live',
    geofences: '/v1/gps/geofences',
    alerts: '/v1/gps/alerts',
  },
  geofences: {
    list: '/v1/geofences',
    create: '/v1/geofences',
  },
  vehicleGps: {
    positions: (id: number | string) => `/v1/vehicles/${id}/positions`,
    trips: (id: number | string) => `/v1/vehicles/${id}/trips`,
    geofencesAssign: (id: number | string) => `/v1/vehicles/${id}/geofences`,
  },
  notifications: {
    list: '/v1/notifications',
    deliveries: '/v1/notification-deliveries',
    unreadCount: '/v1/notifications/unread-count',
    markRead: (id: string) => `/v1/notifications/${id}/mark-read`,
    markAllRead: '/v1/notifications/mark-all-read',
    retry: (id: string) => `/v1/notifications/${id}/retry`,
    destroy: (id: string) => `/v1/notifications/${id}`,
  },
  reservations: {
    list: '/v1/reservations',
    one: (id: number | string) => `/v1/reservations/${id}`,
    create: '/v1/reservations',
    confirm: (id: number | string) => `/v1/reservations/${id}/confirm`,
    cancel: (id: number | string) => `/v1/reservations/${id}/cancel`,
    createMission: (id: number | string) => `/v1/reservations/${id}/create-mission`,
    handoverPickup: (id: number | string) => `/v1/reservations/${id}/handover-pickup`,
    requestExtension: (id: number | string) => `/v1/reservations/${id}/request-extension`,
    handoverReturn: (id: number | string) => `/v1/reservations/${id}/handover-return`,
    damageReport: (id: number | string) => `/v1/reservations/${id}/damage-report`,
    closeBilling: (id: number | string) => `/v1/reservations/${id}/close-billing`,
  },
  rentals: {
    availability: '/v1/rentals/availability',
  },
  missions: {
    list: '/v1/missions',
    one: (id: number | string) => `/v1/missions/${id}`,
    start: (id: number | string) => `/v1/missions/${id}/start`,
    complete: (id: number | string) => `/v1/missions/${id}/complete`,
    checklistItems: (id: number | string) => `/v1/missions/${id}/checklist-items`,
    photos: (id: number | string) => `/v1/missions/${id}/photos`,
  },
  audit: {
    list: '/v1/audit',
    one: (id: string) => `/v1/audit/${id}`,
    forEntity: (entityType: string, entityId: string) =>
      `/v1/entities/${entityType}/${entityId}/audit`,
    exportCsv: '/v1/audit/export.csv',
  },
  ai: {
    overview: '/v1/ai/overview',
    assistantMessages: '/v1/ai/assistant/messages',
    assistantConversations: '/v1/ai/assistant/conversations',
    maintenance: '/v1/ai/predictions/maintenance',
    creditRisk: '/v1/ai/predictions/credit-risk',
    cashFlow: '/v1/ai/predictions/cash-flow',
    vehiclePricing: '/v1/ai/predictions/vehicle-pricing',
    anomalies: '/v1/ai/anomalies',
  },
  settings: {
    users: '/v1/settings/users',
    master: '/v1/settings/master-data',
  },
} as const;
